/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type ItineraryStatus = "archived" | "draft" | "published";

export type Numeric = ColumnType<string, number | string, number | string>;

export type SessionType = "afternoon" | "evening" | "lunch" | "morning";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Activities {
  category_tag: string | null;
  cost_display: string | null;
  created_at: Generated<Timestamp>;
  currency: Generated<string | null>;
  description: string | null;
  estimated_cost: Numeric | null;
  id: Generated<string>;
  itinerary_day_id: string;
  location_address: string | null;
  location_lat: Numeric | null;
  location_lng: Numeric | null;
  location_name: string | null;
  map_link: string | null;
  order_index: number;
  place_id: string | null;
  time_session: SessionType;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface ActivityImages {
  activity_id: string;
  caption: string | null;
  created_at: Generated<Timestamp>;
  display_order: number;
  id: Generated<string>;
  url: string;
}

export interface Bookmarks {
  created_at: Generated<Timestamp>;
  itinerary_id: string;
  user_id: string;
}

export interface Itineraries {
  avg_rating: Generated<Numeric | null>;
  created_at: Generated<Timestamp>;
  currency: Generated<string | null>;
  description: string | null;
  duration: string | null;
  duration_days: number;
  estimated_price_cents: number | null;
  id: Generated<string>;
  is_featured: Generated<boolean>;
  like_count: Generated<number>;
  published_at: Timestamp | null;
  region: string;
  slug: string;
  status: Generated<ItineraryStatus>;
  thumbnail_url: string | null;
  title: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
  view_count: Generated<number>;
}

export interface ItineraryDays {
  created_at: Generated<Timestamp>;
  day_index: number;
  id: Generated<string>;
  itinerary_id: string;
  theme: string | null;
  updated_at: Generated<Timestamp>;
}

export interface ItineraryTags {
  created_at: Generated<Timestamp>;
  itinerary_id: string;
  tag_id: string;
}

export interface ItineraryViews {
  id: Generated<string>;
  ip_hash: string | null;
  itinerary_id: string;
  user_agent: string | null;
  user_id: string | null;
  viewed_at: Generated<Timestamp>;
}

export interface Tags {
  created_at: Generated<Timestamp>;
  icon: string | null;
  id: Generated<string>;
  name: string;
  slug: string;
}

export interface Users {
  avatar_url: string | null;
  bio: string | null;
  created_at: Generated<Timestamp>;
  display_name: string;
  email: string;
  id: Generated<string>;
  is_verified: Generated<boolean>;
  password_hash: string;
  role_key: Generated<string>;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
  username: string;
}

export interface DB {
  activities: Activities;
  activity_images: ActivityImages;
  bookmarks: Bookmarks;
  itineraries: Itineraries;
  itinerary_days: ItineraryDays;
  itinerary_tags: ItineraryTags;
  itinerary_views: ItineraryViews;
  tags: Tags;
  users: Users;
}
